name: ci-sonarcloud-node
on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 14.1
      
      - name: Install modules
        run: npm install

      - name: Test
        run: npm test